# Generated by Django 5.2.7 on 2025-11-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('Kayes', 'Kayes'), ('Koulikoro', 'Koulikoro'), ('Sikasso', 'Sikasso'), ('Ségou', 'Ségou'), ('Mopti', 'Mopti'), ('Tombouctou', 'Tombouctou'), ('Gao', 'Gao'), ('Kidal', 'Kidal'), ('Taoudénit', 'Taoudénit'), ('Ménaka', 'Ménaka'), ('Bamako', 'Bamako')], default='Bamako', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
