# Generated by Django 5.2.7 on 2025-10-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, choices=[('Equipment', 'Equipment'), ('Supplies', 'Supplies'), ('Infrastructure', 'Infrastructure'), ('Labor', 'Labor'), ('Utilities', 'Utilities'), ('Other', 'Other')], max_length=50, null=True)),
            ],
        ),
    ]
